// <auto-generated />
namespace Drop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_StiDeViat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_StiDeViat));
        
        string IMigrationMetadata.Id
        {
            get { return "201906141958399_Add_StiDeViat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
